"""
SQLAlchemy ORM models for the Banking CRM system.

Tables:
    customers          - Core customer profile + financial attributes
    transactions       - Per-customer transaction history
    loan_inquiries     - Customer-initiated loan inquiries
    crm_interactions   - RM-customer interaction history
    recommendations    - Product recommendations generated by agents
    whatsapp_campaigns - Outreach campaign records (simulated)
    agent_logs         - Centralized audit trail of agent/tool execution
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    DateTime,
    ForeignKey,
    Text,
    Boolean,
)
from sqlalchemy.orm import relationship

from backend.database.db import Base


class Customer(Base):
    """Customer master record."""

    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_code = Column(String(20), unique=True, nullable=False, index=True)
    full_name = Column(String(120), nullable=False)
    email = Column(String(120), nullable=False)
    phone = Column(String(25), nullable=False)
    city = Column(String(80), nullable=False)
    age = Column(Integer, nullable=False)
    occupation = Column(String(80), nullable=False)
    annual_income = Column(Float, nullable=False)
    monthly_salary = Column(Float, nullable=False)
    account_balance = Column(Float, nullable=False)
    credit_score = Column(Integer, nullable=False)
    account_type = Column(String(40), nullable=False)  # SAVINGS / SALARY / PREMIUM
    customer_segment = Column(String(40), nullable=False)  # HIGH / MEDIUM / LOW
    has_existing_loan = Column(Boolean, default=False)
    previous_repayment_score = Column(Float, default=1.0)  # 0..1
    onboarding_date = Column(DateTime, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    transactions = relationship("Transaction", back_populates="customer", cascade="all, delete-orphan")
    loan_inquiries = relationship("LoanInquiry", back_populates="customer", cascade="all, delete-orphan")
    crm_interactions = relationship("CRMInteraction", back_populates="customer", cascade="all, delete-orphan")
    recommendations = relationship("Recommendation", back_populates="customer", cascade="all, delete-orphan")
    campaigns = relationship("WhatsAppCampaign", back_populates="customer", cascade="all, delete-orphan")


class Transaction(Base):
    """Customer transaction history."""

    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    transaction_date = Column(DateTime, default=datetime.utcnow, index=True)
    amount = Column(Float, nullable=False)
    transaction_type = Column(String(20), nullable=False)  # CREDIT / DEBIT
    category = Column(String(40), nullable=False)  # SALARY / SHOPPING / EMI etc.
    merchant = Column(String(120), nullable=True)
    balance_after = Column(Float, nullable=False)

    customer = relationship("Customer", back_populates="transactions")


class LoanInquiry(Base):
    """Customer-initiated loan inquiry."""

    __tablename__ = "loan_inquiries"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    loan_type = Column(String(40), nullable=False)  # PERSONAL / HOME / CAR / EDUCATION
    inquiry_amount = Column(Float, nullable=False)
    inquiry_date = Column(DateTime, default=datetime.utcnow, index=True)
    channel = Column(String(40), nullable=False)  # WEB / APP / BRANCH / CALL
    status = Column(String(40), default="OPEN")  # OPEN / CLOSED / CONVERTED

    customer = relationship("Customer", back_populates="loan_inquiries")


class CRMInteraction(Base):
    """Relationship Manager - customer interaction record."""

    __tablename__ = "crm_interactions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    interaction_date = Column(DateTime, default=datetime.utcnow)
    channel = Column(String(40), nullable=False)  # CALL / EMAIL / WHATSAPP / VISIT
    notes = Column(Text, nullable=True)
    sentiment = Column(String(20), default="NEUTRAL")  # POSITIVE / NEUTRAL / NEGATIVE
    rm_name = Column(String(80), nullable=True)

    customer = relationship("Customer", back_populates="crm_interactions")


class Recommendation(Base):
    """Product recommendation produced by the recommendation agent."""

    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    product_code = Column(String(40), nullable=False)
    product_name = Column(String(120), nullable=False)
    recommended_amount = Column(Float, nullable=False)
    interest_rate = Column(Float, nullable=False)
    tenure_months = Column(Integer, nullable=False)
    rationale = Column(Text, nullable=True)
    confidence = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)

    customer = relationship("Customer", back_populates="recommendations")


class WhatsAppCampaign(Base):
    """Simulated WhatsApp outreach campaign record."""

    __tablename__ = "whatsapp_campaigns"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    phone = Column(String(25), nullable=False)
    message = Column(Text, nullable=False)
    status = Column(String(20), default="PENDING")  # SENT / FAILED / PENDING
    sent_at = Column(DateTime, default=datetime.utcnow)
    campaign_run_id = Column(String(60), nullable=True, index=True)

    customer = relationship("Customer", back_populates="campaigns")


class AgentLog(Base):
    """Audit log of agent and tool executions."""

    __tablename__ = "agent_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(60), nullable=False, index=True)
    agent_name = Column(String(80), nullable=False)
    tool_name = Column(String(80), nullable=True)
    step_name = Column(String(80), nullable=True)
    status = Column(String(20), nullable=False)  # STARTED / SUCCESS / FAILED
    reasoning = Column(Text, nullable=True)
    input_payload = Column(Text, nullable=True)
    output_payload = Column(Text, nullable=True)
    error_message = Column(Text, nullable=True)
    duration_ms = Column(Float, default=0.0)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
